const RAW_BASE = "https://raw.githubusercontent.com/ysiemmanuel9-source/app-musica/main/assets/music";

const localTracks = [
  {
    id: "local-001",
    title: "Æternum.f140",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3219352,
    file: "001-ternum-f140.m4a",
    url: `${RAW_BASE}/001-ternum-f140.m4a`
  },
  {
    id: "local-002",
    title: "Agosto",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 5835733,
    file: "002-bad-bunny-agosto.mp3",
    url: `${RAW_BASE}/002-bad-bunny-agosto.mp3`
  },
  {
    id: "local-003",
    title: "Aguacero",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8716263,
    file: "003-bad-bunny-aguacero.mp3",
    url: `${RAW_BASE}/003-bad-bunny-aguacero.mp3`
  },
  {
    id: "local-004",
    title: "Andrea",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 13866504,
    file: "004-bad-bunny-andrea.mp3",
    url: `${RAW_BASE}/004-bad-bunny-andrea.mp3`
  },
  {
    id: "local-005",
    title: "BAILE INoLVIDABLE",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 14979221,
    file: "005-bad-bunny-baile-inolvidable.mp3",
    url: `${RAW_BASE}/005-bad-bunny-baile-inolvidable.mp3`
  },
  {
    id: "local-006",
    title: "BOKeTE",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8904363,
    file: "006-bad-bunny-bokete.mp3",
    url: `${RAW_BASE}/006-bad-bunny-bokete.mp3`
  },
  {
    id: "local-007",
    title: "CAFé CON RON",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9419033,
    file: "007-bad-bunny-caf-con-ron.mp3",
    url: `${RAW_BASE}/007-bad-bunny-caf-con-ron.mp3`
  },
  {
    id: "local-008",
    title: "Callaita",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 10299833,
    file: "008-bad-bunny-callaita.mp3",
    url: `${RAW_BASE}/008-bad-bunny-callaita.mp3`
  },
  {
    id: "local-009",
    title: "Después de la Playa",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9493419,
    file: "009-bad-bunny-despu-s-de-la-playa.mp3",
    url: `${RAW_BASE}/009-bad-bunny-despu-s-de-la-playa.mp3`
  },
  {
    id: "local-010",
    title: "Dos Mil 16",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8622132,
    file: "010-bad-bunny-dos-mil-16.mp3",
    url: `${RAW_BASE}/010-bad-bunny-dos-mil-16.mp3`
  },
  {
    id: "local-011",
    title: "DtMF",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9750528,
    file: "011-bad-bunny-dtmf.mp3",
    url: `${RAW_BASE}/011-bad-bunny-dtmf.mp3`
  },
  {
    id: "local-012",
    title: "Efecto",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8799935,
    file: "012-bad-bunny-efecto.mp3",
    url: `${RAW_BASE}/012-bad-bunny-efecto.mp3`
  },
  {
    id: "local-013",
    title: "El Apagón",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8349139,
    file: "013-bad-bunny-el-apag-n.mp3",
    url: `${RAW_BASE}/013-bad-bunny-el-apag-n.mp3`
  },
  {
    id: "local-014",
    title: "EL CLúB",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9167942,
    file: "014-bad-bunny-el-cl-b.mp3",
    url: `${RAW_BASE}/014-bad-bunny-el-cl-b.mp3`
  },
  {
    id: "local-015",
    title: "Enséñame a Bailar",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7315764,
    file: "015-bad-bunny-ens-ame-a-bailar.mp3",
    url: `${RAW_BASE}/015-bad-bunny-ens-ame-a-bailar.mp3`
  },
  {
    id: "local-016",
    title: "EoO",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8454604,
    file: "016-bad-bunny-eoo.mp3",
    url: `${RAW_BASE}/016-bad-bunny-eoo.mp3`
  },
  {
    id: "local-017",
    title: "KETU TeCRÉ",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 10297567,
    file: "017-bad-bunny-ketu-tecr.mp3",
    url: `${RAW_BASE}/017-bad-bunny-ketu-tecr.mp3`
  },
  {
    id: "local-018",
    title: "KLOuFRENS",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8228692,
    file: "018-bad-bunny-kloufrens.mp3",
    url: `${RAW_BASE}/018-bad-bunny-kloufrens.mp3`
  },
  {
    id: "local-019",
    title: "La Corriente",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8211100,
    file: "019-bad-bunny-la-corriente.mp3",
    url: `${RAW_BASE}/019-bad-bunny-la-corriente.mp3`
  },
  {
    id: "local-020",
    title: "LA MuDANZA",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8785135,
    file: "020-bad-bunny-la-mudanza.mp3",
    url: `${RAW_BASE}/020-bad-bunny-la-mudanza.mp3`
  },
  {
    id: "local-021",
    title: "LO QUE LE PASÓ A HAWAii",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9440967,
    file: "021-bad-bunny-lo-que-le-pas-a-hawaii.mp3",
    url: `${RAW_BASE}/021-bad-bunny-lo-que-le-pas-a-hawaii.mp3`
  },
  {
    id: "local-022",
    title: "Me Fui de Vacaciones",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7513454,
    file: "022-bad-bunny-me-fui-de-vacaciones.mp3",
    url: `${RAW_BASE}/022-bad-bunny-me-fui-de-vacaciones.mp3`
  },
  {
    id: "local-023",
    title: "Me Porto Bonito",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7418295,
    file: "023-bad-bunny-me-porto-bonito.mp3",
    url: `${RAW_BASE}/023-bad-bunny-me-porto-bonito.mp3`
  },
  {
    id: "local-024",
    title: "Moscow Mule",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 10115739,
    file: "024-bad-bunny-moscow-mule.mp3",
    url: `${RAW_BASE}/024-bad-bunny-moscow-mule.mp3`
  },
  {
    id: "local-025",
    title: "Neverita",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7200690,
    file: "025-bad-bunny-neverita.mp3",
    url: `${RAW_BASE}/025-bad-bunny-neverita.mp3`
  },
  {
    id: "local-026",
    title: "NUEVAYoL",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7610535,
    file: "026-bad-bunny-nuevayol.mp3",
    url: `${RAW_BASE}/026-bad-bunny-nuevayol.mp3`
  },
  {
    id: "local-027",
    title: "Ojitos Lindos",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 10611550,
    file: "027-bad-bunny-ojitos-lindos.mp3",
    url: `${RAW_BASE}/027-bad-bunny-ojitos-lindos.mp3`
  },
  {
    id: "local-028",
    title: "Otro Atardecer",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 10056151,
    file: "028-bad-bunny-otro-atardecer.mp3",
    url: `${RAW_BASE}/028-bad-bunny-otro-atardecer.mp3`
  },
  {
    id: "local-029",
    title: "Party",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9382553,
    file: "029-bad-bunny-party.mp3",
    url: `${RAW_BASE}/029-bad-bunny-party.mp3`
  },
  {
    id: "local-030",
    title: "PERFuMITO NUEVO",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8291473,
    file: "030-bad-bunny-perfumito-nuevo.mp3",
    url: `${RAW_BASE}/030-bad-bunny-perfumito-nuevo.mp3`
  },
  {
    id: "local-031",
    title: "PIToRRO DE COCO",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8528889,
    file: "031-bad-bunny-pitorro-de-coco.mp3",
    url: `${RAW_BASE}/031-bad-bunny-pitorro-de-coco.mp3`
  },
  {
    id: "local-032",
    title: "Tarot",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9793590,
    file: "032-bad-bunny-tarot.mp3",
    url: `${RAW_BASE}/032-bad-bunny-tarot.mp3`
  },
  {
    id: "local-033",
    title: "Tití Me Preguntó",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 10026843,
    file: "033-bad-bunny-tit-me-pregunt.mp3",
    url: `${RAW_BASE}/033-bad-bunny-tit-me-pregunt.mp3`
  },
  {
    id: "local-034",
    title: "TURiSTA",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7864699,
    file: "034-bad-bunny-turista.mp3",
    url: `${RAW_BASE}/034-bad-bunny-turista.mp3`
  },
  {
    id: "local-035",
    title: "Un Coco",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 8132625,
    file: "035-bad-bunny-un-coco.mp3",
    url: `${RAW_BASE}/035-bad-bunny-un-coco.mp3`
  },
  {
    id: "local-036",
    title: "Un Ratito",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7353400,
    file: "036-bad-bunny-un-ratito.mp3",
    url: `${RAW_BASE}/036-bad-bunny-un-ratito.mp3`
  },
  {
    id: "local-037",
    title: "Un Verano Sin Ti",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 6200787,
    file: "037-bad-bunny-un-verano-sin-ti.mp3",
    url: `${RAW_BASE}/037-bad-bunny-un-verano-sin-ti.mp3`
  },
  {
    id: "local-038",
    title: "VeLDÁ",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9678394,
    file: "038-bad-bunny-veld.mp3",
    url: `${RAW_BASE}/038-bad-bunny-veld.mp3`
  },
  {
    id: "local-039",
    title: "VOY A LLeVARTE PA PR",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 6516503,
    file: "039-bad-bunny-voy-a-llevarte-pa-pr.mp3",
    url: `${RAW_BASE}/039-bad-bunny-voy-a-llevarte-pa-pr.mp3`
  },
  {
    id: "local-040",
    title: "WELTiTA",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7764299,
    file: "040-bad-bunny-weltita.mp3",
    url: `${RAW_BASE}/040-bad-bunny-weltita.mp3`
  },
  {
    id: "local-041",
    title: "Yo No Soy Celoso",
    artist: "Bad Bunny",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 9505964,
    file: "041-bad-bunny-yo-no-soy-celoso.mp3",
    url: `${RAW_BASE}/041-bad-bunny-yo-no-soy-celoso.mp3`
  },
  {
    id: "local-042",
    title: "Bajo De La Piel",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2728527,
    file: "042-bajo-de-la-piel.m4a",
    url: `${RAW_BASE}/042-bajo-de-la-piel.m4a`
  },
  {
    id: "local-043",
    title: "CR7.f140",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2252580,
    file: "043-cr7-f140.m4a",
    url: `${RAW_BASE}/043-cr7-f140.m4a`
  },
  {
    id: "local-044",
    title: "Cuando El Agua Hirviendo",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2854559,
    file: "044-cuando-el-agua-hirviendo.m4a",
    url: `${RAW_BASE}/044-cuando-el-agua-hirviendo.m4a`
  },
  {
    id: "local-045",
    title: "El Invisible",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3291356,
    file: "045-el-invisible.m4a",
    url: `${RAW_BASE}/045-el-invisible.m4a`
  },
  {
    id: "local-046",
    title: "En Vela.f140",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3445417,
    file: "046-en-vela-f140.m4a",
    url: `${RAW_BASE}/046-en-vela-f140.m4a`
  },
  {
    id: "local-047",
    title: "Frente a Frente.f140",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2843180,
    file: "047-frente-a-frente-f140.m4a",
    url: `${RAW_BASE}/047-frente-a-frente-f140.m4a`
  },
  {
    id: "local-048",
    title: "Jangadero",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 4371783,
    file: "048-jangadero.m4a",
    url: `${RAW_BASE}/048-jangadero.m4a`
  },
  {
    id: "local-049",
    title: "La Vida Era Más Corta",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3170533,
    file: "049-la-vida-era-m-s-corta.m4a",
    url: `${RAW_BASE}/049-la-vida-era-m-s-corta.m4a`
  },
  {
    id: "local-050",
    title: "Llora Llora",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3944606,
    file: "050-llora-llora.m4a",
    url: `${RAW_BASE}/050-llora-llora.m4a`
  },
  {
    id: "local-051",
    title: "Lucia",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3062076,
    file: "051-lucia.m4a",
    url: `${RAW_BASE}/051-lucia.m4a`
  },
  {
    id: "local-052",
    title: "Luciérnagas",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3024303,
    file: "052-luci-rnagas.m4a",
    url: `${RAW_BASE}/052-luci-rnagas.m4a`
  },
  {
    id: "local-053",
    title: "MDLD.f140",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2266296,
    file: "053-mdld-f140.m4a",
    url: `${RAW_BASE}/053-mdld-f140.m4a`
  },
  {
    id: "local-054",
    title: "MmmM",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 3459429,
    file: "054-mmmm.m4a",
    url: `${RAW_BASE}/054-mmmm.m4a`
  },
  {
    id: "local-055",
    title: "No Soy Amigo de Todos.f140",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2315025,
    file: "055-no-soy-amigo-de-todos-f140.m4a",
    url: `${RAW_BASE}/055-no-soy-amigo-de-todos-f140.m4a`
  },
  {
    id: "local-056",
    title: "Radamel",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 1341342,
    file: "056-radamel.m4a",
    url: `${RAW_BASE}/056-radamel.m4a`
  },
  {
    id: "local-057",
    title: "Recordé",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2913638,
    file: "057-record.m4a",
    url: `${RAW_BASE}/057-record.m4a`
  },
  {
    id: "local-058",
    title: "Solifican12",
    artist: "Emmanuel Music",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 2708536,
    file: "058-solifican12.m4a",
    url: `${RAW_BASE}/058-solifican12.m4a`
  },
  {
    id: "local-059",
    title: "444",
    artist: "Yan Block",
    album: "Musica local",
    albumId: "local-library",
    duration: "--:--",
    bytes: 7052139,
    file: "059-yan-block-444.mp3",
    url: `${RAW_BASE}/059-yan-block-444.mp3`
  },
];

export const localAlbums = [
  {
    id: "local-library",
    title: "Musica local",
    artist: "Emmanuel",
    artwork: null,
    year: "2026",
    downloads: localTracks.length,
    local: true,
    tracks: localTracks
  }
];

export default localAlbums;
